#!/usr/bin/env bash
# =============================================================================
# setup_domain.sh — SSL + nginx setup for neurocommenting.com
#
# VPS: 176.124.221.253, user: deploy, path: /opt/neuro-commenting
#
# PREREQUISITES before running this script:
#   1. DNS A-records must already point to the VPS:
#      - neurocommenting.com    -> 176.124.221.253
#      - www.neurocommenting.com -> 176.124.221.253
#   2. SSH access: ssh deploy@176.124.221.253
#   3. Run as root (or with sudo) on the VPS
#
# Usage:
#   scp scripts/setup_domain.sh deploy@176.124.221.253:/tmp/
#   ssh deploy@176.124.221.253 "sudo bash /tmp/setup_domain.sh"
#
# The script is idempotent — safe to re-run.
# =============================================================================

set -euo pipefail

DOMAIN="neurocommenting.com"
DOMAIN_WWW="www.neurocommenting.com"
OLD_DOMAIN="176-124-221-253.sslip.io"
NGINX_CONF="/etc/nginx/sites-available/${DOMAIN}"
NGINX_LINK="/etc/nginx/sites-enabled/${DOMAIN}"
EMAIL="admin@neurocommenting.com"
UPSTREAM="http://127.0.0.1:8081"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log()  { echo -e "${GREEN}[OK]${NC} $*"; }
warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
err()  { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ---------------------------------------------------------------------------
# 0. Pre-flight checks
# ---------------------------------------------------------------------------
echo "============================================"
echo " neurocommenting.com SSL + nginx setup"
echo "============================================"
echo ""

if [[ $EUID -ne 0 ]]; then
  err "This script must be run as root (use sudo)."
fi

# Check nginx is installed
if ! command -v nginx &>/dev/null; then
  err "nginx is not installed. Install it first: apt install nginx"
fi

# Check DNS resolution BEFORE requesting a certificate
echo "Checking DNS for ${DOMAIN}..."
RESOLVED_IP=$(dig +short "${DOMAIN}" A 2>/dev/null | head -1 || true)
if [[ "${RESOLVED_IP}" != "176.124.221.253" ]]; then
  err "DNS A-record for ${DOMAIN} does not resolve to 176.124.221.253 (got: '${RESOLVED_IP}').
  Set up DNS first, wait for propagation, then re-run this script."
fi
log "DNS A-record for ${DOMAIN} -> ${RESOLVED_IP}"

RESOLVED_WWW=$(dig +short "${DOMAIN_WWW}" A 2>/dev/null | head -1 || true)
if [[ "${RESOLVED_WWW}" != "176.124.221.253" ]]; then
  warn "DNS A-record for ${DOMAIN_WWW} does not resolve to 176.124.221.253 (got: '${RESOLVED_WWW}').
  www redirect will not work until DNS is set. Continuing without www in the certificate."
  CERT_DOMAINS="-d ${DOMAIN}"
  INCLUDE_WWW=false
else
  log "DNS A-record for ${DOMAIN_WWW} -> ${RESOLVED_WWW}"
  CERT_DOMAINS="-d ${DOMAIN} -d ${DOMAIN_WWW}"
  INCLUDE_WWW=true
fi

# ---------------------------------------------------------------------------
# 1. Install certbot if missing
# ---------------------------------------------------------------------------
echo ""
echo "--- Step 1: Certbot ---"

if command -v certbot &>/dev/null; then
  log "certbot is already installed: $(certbot --version 2>&1)"
else
  warn "certbot not found. Installing..."
  apt-get update -qq
  apt-get install -y -qq certbot python3-certbot-nginx
  if command -v certbot &>/dev/null; then
    log "certbot installed: $(certbot --version 2>&1)"
  else
    err "Failed to install certbot."
  fi
fi

# Also ensure the nginx plugin is available
if ! dpkg -l python3-certbot-nginx &>/dev/null 2>&1; then
  warn "Installing python3-certbot-nginx plugin..."
  apt-get install -y -qq python3-certbot-nginx
fi
log "certbot nginx plugin is available."

# ---------------------------------------------------------------------------
# 2. Back up existing nginx config
# ---------------------------------------------------------------------------
echo ""
echo "--- Step 2: Backup existing nginx config ---"

BACKUP_DIR="/etc/nginx/backups/$(date +%Y%m%d_%H%M%S)"
mkdir -p "${BACKUP_DIR}"
cp -a /etc/nginx/sites-available/ "${BACKUP_DIR}/sites-available/" 2>/dev/null || true
cp -a /etc/nginx/sites-enabled/  "${BACKUP_DIR}/sites-enabled/"  2>/dev/null || true
log "Backed up nginx config to ${BACKUP_DIR}"

# ---------------------------------------------------------------------------
# 3. Write new nginx config (HTTP-only, for certbot validation)
# ---------------------------------------------------------------------------
echo ""
echo "--- Step 3: Write nginx config for ${DOMAIN} ---"

# Build server_name line
if [[ "${INCLUDE_WWW}" == true ]]; then
  SERVER_NAMES="${DOMAIN} ${DOMAIN_WWW}"
else
  SERVER_NAMES="${DOMAIN}"
fi

cat > "${NGINX_CONF}" <<NGINX_EOF
# neurocommenting.com — generated by setup_domain.sh
# Phase 1: HTTP-only (certbot will add SSL blocks)

server {
    listen 80;
    listen [::]:80;
    server_name ${SERVER_NAMES};

    client_max_body_size 10m;

    location / {
        proxy_pass ${UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 120s;
    }
}
NGINX_EOF

log "Wrote ${NGINX_CONF}"

# Enable the site
if [[ ! -L "${NGINX_LINK}" ]]; then
  ln -s "${NGINX_CONF}" "${NGINX_LINK}"
  log "Symlinked ${NGINX_LINK}"
else
  log "Symlink ${NGINX_LINK} already exists"
fi

# Test nginx config before reload
nginx -t 2>&1 || err "nginx config test failed! Check ${NGINX_CONF}"
log "nginx config test passed"

# Reload to apply HTTP-only config (needed for certbot HTTP-01 challenge)
systemctl reload nginx
log "nginx reloaded with HTTP config"

# ---------------------------------------------------------------------------
# 4. Obtain Let's Encrypt certificate
# ---------------------------------------------------------------------------
echo ""
echo "--- Step 4: Obtain SSL certificate ---"

CERT_PATH="/etc/letsencrypt/live/${DOMAIN}/fullchain.pem"

if [[ -f "${CERT_PATH}" ]]; then
  log "Certificate already exists at ${CERT_PATH}"
  echo "    To force renewal: certbot renew --force-renewal --cert-name ${DOMAIN}"
  CERT_EXISTS=true
else
  CERT_EXISTS=false
  echo "Requesting certificate for: ${CERT_DOMAINS}"
  # shellcheck disable=SC2086
  certbot certonly \
    --nginx \
    ${CERT_DOMAINS} \
    --email "${EMAIL}" \
    --agree-tos \
    --no-eff-email \
    --non-interactive \
    --keep-until-expiring \
    --redirect
  if [[ -f "${CERT_PATH}" ]]; then
    log "Certificate obtained successfully"
  else
    err "Certificate was not created. Check certbot output above."
  fi
fi

# ---------------------------------------------------------------------------
# 5. Write final nginx config with SSL + redirects
# ---------------------------------------------------------------------------
echo ""
echo "--- Step 5: Write final nginx config with SSL ---"

# Determine cert path (could differ if cert already existed under a different name)
CERT_NAME="${DOMAIN}"
if [[ ! -d "/etc/letsencrypt/live/${CERT_NAME}" ]]; then
  # Try to find the cert
  CERT_NAME=$(certbot certificates 2>/dev/null | grep "Certificate Name:" | grep -i neuro | head -1 | awk '{print $NF}' || echo "${DOMAIN}")
fi

CERT_DIR="/etc/letsencrypt/live/${CERT_NAME}"
if [[ ! -d "${CERT_DIR}" ]]; then
  err "Cannot find certificate directory. Expected: ${CERT_DIR}"
fi
log "Using certificate from ${CERT_DIR}"

# Build www redirect block only if www DNS is set
WWW_REDIRECT_BLOCK=""
if [[ "${INCLUDE_WWW}" == true ]]; then
  WWW_REDIRECT_BLOCK="
# --- www -> non-www redirect (HTTPS) ---
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ${DOMAIN_WWW};

    ssl_certificate     ${CERT_DIR}/fullchain.pem;
    ssl_certificate_key ${CERT_DIR}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://${DOMAIN}\$request_uri;
}"
fi

cat > "${NGINX_CONF}" <<NGINX_EOF
# ==========================================================================
# neurocommenting.com — generated by setup_domain.sh
# Last updated: $(date -u '+%Y-%m-%d %H:%M UTC')
# ==========================================================================

# --- HTTP -> HTTPS redirect ---
server {
    listen 80;
    listen [::]:80;
    server_name ${SERVER_NAMES};
    return 301 https://${DOMAIN}\$request_uri;
}
${WWW_REDIRECT_BLOCK}

# --- Main HTTPS server ---
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${DOMAIN};

    ssl_certificate     ${CERT_DIR}/fullchain.pem;
    ssl_certificate_key ${CERT_DIR}/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    client_max_body_size 10m;

    location / {
        proxy_pass ${UPSTREAM};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 120s;
        proxy_buffering off;
    }
}
NGINX_EOF

log "Wrote final SSL config to ${NGINX_CONF}"

# Test and reload
nginx -t 2>&1 || err "nginx config test failed after SSL setup! Restoring backup..."
systemctl reload nginx
log "nginx reloaded with SSL config"

# ---------------------------------------------------------------------------
# 6. Keep old sslip.io config working (do not remove it)
# ---------------------------------------------------------------------------
echo ""
echo "--- Step 6: Verify old sslip.io config ---"

OLD_CONF_EXISTS=false
for f in /etc/nginx/sites-enabled/*; do
  if grep -q "${OLD_DOMAIN}" "$f" 2>/dev/null; then
    OLD_CONF_EXISTS=true
    log "Old ${OLD_DOMAIN} config still active in $f — keeping it for backward compatibility"
    break
  fi
done

if [[ "${OLD_CONF_EXISTS}" == false ]]; then
  warn "No active config found for ${OLD_DOMAIN}. Old URL will stop working."
fi

# ---------------------------------------------------------------------------
# 7. Verify auto-renewal
# ---------------------------------------------------------------------------
echo ""
echo "--- Step 7: Verify auto-renewal ---"

# Check if systemd timer is active
if systemctl is-active --quiet certbot.timer 2>/dev/null; then
  log "certbot.timer is active (auto-renewal enabled)"
elif crontab -l 2>/dev/null | grep -q certbot; then
  log "certbot cron job found (auto-renewal enabled)"
else
  warn "No auto-renewal detected. Adding cron job..."
  (crontab -l 2>/dev/null; echo "0 3 * * * certbot renew --quiet --deploy-hook 'systemctl reload nginx'") | crontab -
  log "Added daily certbot renewal cron job at 03:00"
fi

# Dry-run renewal test
echo "Running certbot renewal dry-run..."
if certbot renew --dry-run --quiet 2>&1; then
  log "Renewal dry-run passed"
else
  warn "Renewal dry-run had issues. Check: certbot renew --dry-run"
fi

# ---------------------------------------------------------------------------
# 8. Final verification
# ---------------------------------------------------------------------------
echo ""
echo "--- Step 8: Final verification ---"

# Test HTTPS connectivity
echo "Testing https://${DOMAIN}/health ..."
HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 "https://${DOMAIN}/health" 2>/dev/null || echo "000")

if [[ "${HTTP_CODE}" == "200" ]]; then
  log "https://${DOMAIN}/health returned 200"
elif [[ "${HTTP_CODE}" == "000" ]]; then
  warn "Could not connect to https://${DOMAIN}/health (DNS may not have propagated yet)"
else
  warn "https://${DOMAIN}/health returned ${HTTP_CODE} (app may need restart)"
fi

# Test HTTP->HTTPS redirect
HTTP_REDIRECT=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 "http://${DOMAIN}/" 2>/dev/null || echo "000")
if [[ "${HTTP_REDIRECT}" == "301" ]]; then
  log "HTTP -> HTTPS redirect working (301)"
else
  warn "HTTP redirect returned ${HTTP_REDIRECT} (expected 301)"
fi

# Test www redirect if applicable
if [[ "${INCLUDE_WWW}" == true ]]; then
  WWW_REDIRECT=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 "https://${DOMAIN_WWW}/" 2>/dev/null || echo "000")
  if [[ "${WWW_REDIRECT}" == "301" ]]; then
    log "www -> non-www redirect working (301)"
  else
    warn "www redirect returned ${WWW_REDIRECT} (expected 301)"
  fi
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------
echo ""
echo "============================================"
echo " SETUP COMPLETE"
echo "============================================"
echo ""
echo " Domain:        https://${DOMAIN}"
echo " Certificate:   ${CERT_DIR}/fullchain.pem"
echo " Nginx config:  ${NGINX_CONF}"
echo " Backup:        ${BACKUP_DIR}"
echo " Old domain:    https://${OLD_DOMAIN} (still active)"
echo ""
echo " Next steps:"
echo "   1. Update CORS_ALLOWED_ORIGINS in .env to include https://${DOMAIN}"
echo "   2. Update BotFather /setdomain to ${DOMAIN}"
echo "   3. Update CLAUDE.md and change_register.md with the new public URL"
echo "   4. Test: curl -I https://${DOMAIN}/health"
echo ""

# ---------------------------------------------------------------------------
# Post-setup: reminder about app .env
# ---------------------------------------------------------------------------
echo " IMPORTANT: Update /opt/neuro-commenting/.env:"
echo "   CORS_ALLOWED_ORIGINS=https://${DOMAIN},https://${OLD_DOMAIN}"
echo "   PUBLIC_URL=https://${DOMAIN}"
echo ""
echo " Then restart the app:"
echo "   cd /opt/neuro-commenting && docker compose restart ops_api"
echo ""
